### ISSUE TITLE
_eos

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-sssp-workflow#83]
```
03/30/2022 03:17:24 PM <26320> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [65218|_EquationOfStateWorkChain|inspect_eos]: The birch murnaghan fitting results are: {'energy0': -1922.902594, 'volume0': 28.5515551, 'residuals0': 0, 'bulk_deriv0': -22.2951885, 'num_of_atoms': 1, 'volume0_unit': 'A^3', 'bulk_modulus0': 0.8782314, 'bulk_modulus0_GPa': 140.7082513, 'bulk_modulus0_unit': 'eV A^3', 'bulk_modulus0_GPa_unit': 'GPa'}
03/30/2022 03:17:25 PM <26320> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [65214|_EquationOfStateWorkChain|on_except]: Traceback (most recent call last):
  File "/home/jyu/miniconda3/envs/aiida-sssp-dev/lib/python3.9/site-packages/plumpy/process_states.py", line 231, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File "/home/jyu/miniconda3/envs/aiida-sssp-dev/lib/python3.9/site-packages/aiida/engine/processes/workchains/workchain.py", line 214, in _do_step
    finished, stepper_result = self._stepper.step()
  File "/home/jyu/miniconda3/envs/aiida-sssp-dev/lib/python3.9/site-packages/plumpy/workchains.py", line 299, in step 
    finished, result = self._child_stepper.step()
  File "/home/jyu/miniconda3/envs/aiida-sssp-dev/lib/python3.9/site-packages/plumpy/workchains.py", line 250, in step 
    return True, self._fn(self._workchain)
  File "/home/jyu/Projects/WP-SSSP/aiida-sssp-workflow/aiida_sssp_workflow/workflows/evaluate/_eos.py", line 177, in inspect_eos
    f"The birch murnaghan fitting results are: {output_birch_murnaghan_fit.get_dict()}"
AttributeError: 'dict' object has no attribute 'get_dict'

03/30/2022 03:17:25 PM <26320> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [65158|DeltaWorkChain|inspect_eos]: _EquationOfStateWorkChain failed with exit status None
03/30/2022 03:17:25 PM <26320> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [65158|DeltaWorkChain|on_except]: Traceback (most recent call last):
  File "/home/jyu/miniconda3/envs/aiida-sssp-dev/lib/python3.9/site-packages/plumpy/process_states.py", line 231, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File "/home/jyu/miniconda3/envs/aiida-sssp-dev/lib/python3.9/site-packages/aiida/engine/processes/workchains/workchain.py", line 214, in _do_step
    finished, stepper_result = self._stepper.step()
  File "/home/jyu/miniconda3/envs/aiida-sssp-dev/lib/python3.9/site-packages/plumpy/workchains.py", line 299, in step 
    finished, result = self._child_stepper.step()
  File "/home/jyu/miniconda3/envs/aiida-sssp-dev/lib/python3.9/site-packages/plumpy/workchains.py", line 250, in step 
    return True, self._fn(self._workchain)
  File "/home/jyu/Projects/WP-SSSP/aiida-sssp-workflow/aiida_sssp_workflow/workflows/evaluate/_delta.py", line 163, in finalize
    output_bmf = self.outputs["eos"].get("output_birch_murnaghan_fit")
KeyError: 'eos'
```

**Comment by unkcpz** [comment]
It is caused by failing of birch_murnaghan_fit calcfunction with `Finished [100] get spurious volume0=0.`. Add a handler in _eos workchain. The calculation problem caused from that in test protocol running, for some configurations, the EOS not able to process to give a volume makes sense. The typical volume-energy pairs that cause the issue here are:

```
PK: 66085
{
    "energies": {
        "0": -1923.2319474241,
        "1": -1923.2533718987,
        "2": -1923.2558312635,
        "3": -1923.272249932,
        "4": -1923.2727035458
    },
    "energy_unit": "eV",
    "num_of_atoms": 1,
    "volume_unit": "A^3",
    "volumes": {
        "0": 22.190777618249,
        "1": 22.653085483834,
        "2": 23.115393351606,
        "3": 23.577701218334,
        "4": 24.040009086167
    }
}
```
